# Generated by Django 3.2.3 on 2021-05-21 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administratorzy',
            fields=[
                ('id_administratorzy', models.AutoField(primary_key=True, serialize=False)),
                ('nazwisko', models.CharField(max_length=40)),
                ('imię', models.CharField(max_length=40)),
                ('adres_mailowy', models.CharField(max_length=40)),
                ('hasło', models.CharField(max_length=20)),
                ('nr_telefonu', models.CharField(blank=True, max_length=9, null=True)),
            ],
            options={
                'db_table': 'administratorzy',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DniTygodnia',
            fields=[
                ('id_dnia_tygodnia', models.AutoField(primary_key=True, serialize=False)),
                ('dzień', models.CharField(max_length=11)),
            ],
            options={
                'db_table': 'dni_tygodnia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GodzinyOtwarcia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('godz_otw', models.TimeField()),
                ('godz_zamkn', models.TimeField()),
            ],
            options={
                'db_table': 'godziny_otwarcia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Kategoria',
            fields=[
                ('id_kategorii', models.AutoField(primary_key=True, serialize=False)),
                ('nazwa_kategorii', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'kategoria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Obiekt',
            fields=[
                ('id_obiektu', models.AutoField(primary_key=True, serialize=False)),
                ('nazwa', models.CharField(max_length=40)),
                ('adres', models.CharField(max_length=40)),
                ('ułatwienia_dla_niepełnosprawnych', models.TextField()),
            ],
            options={
                'db_table': 'obiekt',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pracownicy',
            fields=[
                ('id_pracownika', models.AutoField(primary_key=True, serialize=False)),
                ('imię', models.CharField(max_length=40)),
                ('nazwisko', models.CharField(max_length=40)),
                ('adres_mailowy', models.CharField(max_length=40)),
                ('hasło', models.CharField(max_length=20)),
                ('kontakt', models.CharField(blank=True, max_length=40, null=True)),
                ('data_założenia_konta', models.DateField()),
                ('czy_aktywowany', models.TextField()),
            ],
            options={
                'db_table': 'pracownicy',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Punkt',
            fields=[
                ('id_punktu', models.AutoField(primary_key=True, serialize=False)),
                ('nazwa', models.CharField(max_length=40)),
                ('zdjęcie', models.TextField(blank=True, null=True)),
                ('informacje', models.CharField(blank=True, max_length=50, null=True)),
                ('nr_telefonu', models.CharField(blank=True, max_length=9, null=True)),
                ('długość_geograficzna', models.FloatField()),
                ('szerokość_geograficzna', models.FloatField()),
            ],
            options={
                'db_table': 'punkt',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PunktPracownicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'punkt_pracownicy',
                'managed': False,
            },
        ),
    ]
