# Generated by Django 3.2.4 on 2021-06-21 20:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DniTygodnia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dzień', models.CharField(max_length=12)),
            ],
            options={
                'verbose_name_plural': 'Dni tygodnia',
                'db_table': 'myapp_dnitygodnia',
                'ordering': ('id', 'dzień'),
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Kategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa_kategorii', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Kategorie',
                'db_table': 'myapp_kategoria',
                'ordering': ('id', 'nazwa_kategorii'),
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Obiekt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=40)),
                ('adres', models.CharField(max_length=40)),
                ('ułatwienia_dla_niepełnosprawnych', models.CharField(choices=[('1', 'tak'), ('0', 'nie')], max_length=10, verbose_name='Ułatwienia dla niepełnosprawnych')),
                ('długość_geograficzna', models.FloatField()),
                ('szerokość_geograficzna', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'Obiekty',
                'db_table': 'myapp_obiekt',
                'ordering': ('id', 'nazwa'),
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Pracownicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kontakt', models.EmailField(max_length=254, verbose_name='Email')),
                ('czy_aktywowany', models.CharField(choices=[('1', 'tak'), ('0', 'nie')], max_length=10, verbose_name='Czy aktywny')),
            ],
            options={
                'verbose_name_plural': 'Pracownicy',
                'db_table': 'myapp_pracownicy',
                'ordering': ('id',),
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Punkt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=40)),
                ('zdjęcie', models.TextField(blank=True, db_column='zdjęcie', null=True)),
                ('informacje', models.CharField(blank=True, max_length=50, null=True)),
                ('nr_telefonu', models.CharField(blank=True, max_length=9, null=True, verbose_name='Telefon')),
                ('długość_geograficzna', models.FloatField()),
                ('szerokość_geograficzna', models.FloatField()),
                ('kategoria_id_kategorii', models.ForeignKey(db_column='kategoria_id_kategorii', on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.kategoria', verbose_name='Kategoria')),
                ('obiekt_id_obiektu', models.ForeignKey(db_column='obiekt_id_obiektu', on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.obiekt', verbose_name='Nazwa obiektu')),
            ],
            options={
                'verbose_name_plural': 'Punkty',
                'db_table': 'myapp_punkt',
                'ordering': ('id', 'nazwa'),
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PunktPracownicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pracownicy_id_pracownika', models.ForeignKey(db_column='pracownicy_id_pracownika', on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.pracownicy', verbose_name='Pracownik')),
                ('punkt_id_punktu', models.ForeignKey(db_column='punkt_id_punktu', on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.punkt', verbose_name='Nazwa punktu')),
            ],
            options={
                'verbose_name_plural': 'Punkty - Pracownicy',
                'db_table': 'myapp_punktpracownicy',
                'ordering': ('punkt_id_punktu', 'pracownicy_id_pracownika'),
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='pracownicy',
            name='punkt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.punkt'),
        ),
        migrations.AddField(
            model_name='pracownicy',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='GodzinyOtwarcia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('godz_otw', models.TimeField(help_text='Wprowadź godzinę od 00:00 do 23:59', verbose_name='Godzina otwarcia')),
                ('godz_zamkn', models.TimeField(help_text='Wprowadź godzinę od 00:00 do 23:59', verbose_name='Godzina zamknięcia')),
                ('dni_tygodnia_id_dnia_tygodnia', models.ForeignKey(db_column='dni_tygodnia_id_dnia_tygodnia', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.dnitygodnia', verbose_name='Dzień tygodnia')),
                ('punkt_id_punktu', models.ForeignKey(db_column='punkt_id_punktu', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.punkt', verbose_name='Nazwa punktu')),
            ],
            options={
                'verbose_name_plural': 'Godziny otwarcia',
                'db_table': 'myapp_godzinyotwarcia',
                'ordering': ('dni_tygodnia_id_dnia_tygodnia', 'punkt_id_punktu'),
                'managed': True,
            },
        ),
    ]
