# Generated by Django 3.2.4 on 2021-06-22 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20210622_0250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pracownicy',
            name='kontakt',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='Telefon'),
        ),
    ]
