# Generated by Django 3.2.4 on 2021-06-22 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20210622_0303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pracownicy',
            name='kontakt',
            field=models.CharField(max_length=20, verbose_name='Telefon'),
        ),
    ]
