# Generated by Django 3.2.4 on 2021-06-22 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20210622_0309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pracownicy',
            name='kontakt',
            field=models.CharField(db_column='kontakt', max_length=9, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='pracownicy',
            name='punkt',
            field=models.ForeignKey(db_column='punkt_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.punkt'),
        ),
    ]
