# Generated by Django 3.2.4 on 2021-06-22 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20210622_0320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obiekt',
            name='ułatwienia_dla_niepełnosprawnych',
            field=models.CharField(choices=[('1', 'tak'), ('0', 'nie')], max_length=10, verbose_name='Ułatwienia dla niepełnosprawnych'),
        ),
        migrations.AlterField(
            model_name='pracownicy',
            name='czy_aktywowany',
            field=models.CharField(choices=[('1', 'tak'), ('0', 'nie')], max_length=10, verbose_name='Czy aktywny'),
        ),
        migrations.AlterField(
            model_name='pracownicy',
            name='punkt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.punkt'),
        ),
    ]
