# Generated by Django 3.2 on 2021-04-25 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Strona', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
